#!/usr/bin/env bash
# Script to transfers file from client to server:
# 4 parameter only:
## 1. The file path to be transferred
## 2. The server IP
## 3. The username
## 4. The SSH private key path

if [ "$#" -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
