#!/usr/bin/env bash
# script to installs nginx and configure the web server
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index_nginx.html
service nginx start
