#!/usr/bin/env bash
# Script to transfers file from client to server:
# takes 4 parameters:
## 1. Path to the file to be transferred
## 2. IP of the server we want to transfer the file to
## 3. Username scp connects with
## 4. Path to the SSH private key

if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
