#!/usr/bin/env bash
# it pings an IP address passed as an argument

# the ip variable
IP="${1}"

# the filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
