#!/usr/bin/env bash
#script to configure web server to run as nginx user on port 8080.

# Config by replacing '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# change port 80 with 8080 in the sites-available config file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give read and write permissions to the config file
chmod 644 /etc/nginx/nginx.conf
# apache interferance may occure with nginx so kill the process if it is running
pkill apache2
# with the new nginx user, start the nginx service
sudo -u nginx service nginx start
